In [8]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
from csmarapi.CsmarService import CsmarService
from csmarapi.ReportUtil import ReportUtil

csmar = CsmarService()
csmar.login('2020311334@email.cufe.edu.cn', '20021020liu')

Sat 03 Jun 2023 23:02:45 CsmarService.py INFO User login succeed

In [21]:
from csmarapi.CsmarService import CsmarService
from csmarapi.ReportUtil import ReportUtil

csmar = CsmarService()
csmar.login('2020311820@email.cufe.edu.cn', 'ZZFzzf1231')

Sat 03 Jun 2023 23:40:53 CsmarService.py INFO User login succeed

In [12]:
from csmarapi.CsmarService import CsmarService
from csmarapi.ReportUtil import ReportUtil

csmar = CsmarService()
csmar.login('1800011778@pku.edu.cn', 'yygwzzjsC1')

Sat 03 Jun 2023 23:22:08 CsmarService.py INFO User login succeed

In [16]:
from csmarapi.CsmarService import CsmarService
from csmarapi.ReportUtil import ReportUtil

csmar = CsmarService()
csmar.login('1900012943@pku.edu.cn', 'cyd0819')

Sat 03 Jun 2023 23:28:18 CsmarService.py INFO User login succeed

In [3]:
start = '1990-01-01'
end = '2023-06-01'

In [46]:
data1 = csmar.query(['Stkcd', 'Stknme', 'Listdt', 'Cuntrycd', 'Conme', 'Conme_en', 'Indcd', 'Indnme', 'Nindcd', 'Nindnme', 'Nnindcd', 'Nnindnme', 
                     'Estbdt', 'PROVINCE', 'PROVINCECODE', 'CITY', 'CITYCODE', 'OWNERSHIPTYPE', 'OWNERSHIPTYPECODE', 'Favaldt', 'Curtrd', 
                     'Ipoprm', 'Ipoprc', 'Ipocur', 'Nshripo', 'Parvcur', 'Ipodt', 'Parval', 'Sctcd', 'Statco', 'Crcd', 'Statdt', 'Commnt'], 
                    'Listdt LIKE \'%____-__-__%\'', 'TRD_Co', start, end)
df1 = pd.DataFrame(data1)
df1.rename(columns={'Stkcd': '证券代码', 'Stknme': '证券简称', 'Listdt': '上市日期', 'Cuntrycd': '国家代码', 'Conme': '公司全称', 
                    'Conme_en': '公司英文全称', 'Indcd': '行业代码A', 'Indnme': '行业名称A', 'Nindcd': '行业代码B', 'Nindnme': '行业名称B', 
                    'Nnindcd': '行业代码C', 'Nnindnme': '行业名称C', 'Estbdt': '公司成立日期', 'PROVINCE': '所属省份', 'PROVINCECODE': '所属省份代码', 
                    'CITY': '所属城市', 'CITYCODE': '所属城市代码', 'OWNERSHIPTYPE': '上市公司经营性质', 'OWNERSHIPTYPECODE': '上市公司经营性质编码', 
                    'Favaldt': '数据库最早交易记录的日期', 'Curtrd': '数据库中交易数据的计量货币', 'Ipoprm': '股票发行溢价', 'Ipoprc': '发行价格', 
                    'Ipocur': '发行价格的计量货币', 'Nshripo': '发行数量', 'Parvcur': '股票面值的计量货币', 'Ipodt': '发行日期', 'Parval': '股票面值', 
                    'Sctcd': '区域码', 'Statco': '公司活动情况', 'Crcd': 'AB股交叉码', 'Statdt': '情况变动日', 'Commnt': 'H股交叉码'}, 
           inplace=True)
df1['证券代码'] = df1['证券代码'].astype('int')
df1.to_csv('../../data/csmar/公司文件.csv', index=False, encoding='utf-8-sig')
df1

,国家代码,证券代码,证券简称,公司全称,公司英文全称,行业代码A,行业名称A,行业代码B,行业名称B,行业代码C,...,公司活动情况,AB股交叉码,情况变动日,H股交叉码,所属省份,所属省份代码,所属城市,所属城市代码,上市公司经营性质,上市公司经营性质编码
0,10,1,平安银行,平安银行股份有限公司,"Ping An Bank Co., Ltd.",0001,金融,I01,银行业,J66,...,A,None,2023-04-27,None,广东省,440000,深圳市,440300,私营企业,P0306
1,10,2,万科A,万科企业股份有限公司,"China Vanke Co., Ltd.",0003,房地产,J,房地产业,K70,...,A,None,2023-04-27,02202,广东省,440000,深圳市,440300,国营或国有控股,P0301
2,10,3,PT 金田A,金田实业(集团)股份有限公司,"Gintian Industry (Group) Co., Ltd.",0004,综合,M,综合类,S90,...,D,None,2002-06-14,None,广东省,440000,深圳市,440300,国营或国有控股,P0301
3,10,4,ST 国华,深圳国华网安科技股份有限公司,"Shenzhen Cau Technology Co., Ltd.",0002,公用事业,G87,计算机应用服务业,I65,...,A,None,2023-04-27,None,广东省,440000,深圳市,440300,私营企业,P0306
4,10,5,ST 星源,深圳世纪星源股份有限公司,Shenzhen Fountain Corporation,0002,公用事业,K99,其他社会服务业,N77,...,A,None,2023-04-27,None,广东省,440000,深圳市,440300,中外合资,P0303
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5475,10,900952,锦港B股,锦州港股份有限公司,"Jinzhou Port Co., Ltd.",0002,公用事业,F07,水上运输业,G55,...,A,600190,2023-04-27,None,辽宁省,210000,锦州市,210700,国营或国有控股,P0301
5476,10,900953,凯马B,恒天凯马股份有限公司,"Kama Co., Ltd.",0005,工业,C75,交通运输设备制造业,C36,...,A,None,2023-04-27,None,上海市,310000,上海市,310000,国营或国有控股,P0301
5477,10,900955,退市海B,海航创新股份有限公司,"HNA Innovation Co., Ltd.",0003,房地产,J,房地产业,K70,...,D,None,2022-07-13,None,海南省,460000,三亚市,460200,中外合资,P0303
5478,10,900956,东贝B股,黄石东贝电器股份有限公司,"Huangshi Dongbei Electrical Appliance Co., Ltd.",0005,工业,C71,普通机械制造业,C34,...,D,None,2020-11-23,None,湖北省,420000,黄石市,420200,国营或国有控股,P0301
5479,10,900957,凌云B股,上海凌云实业发展股份有限公司,"Shanghai Lingyun Industries Development Co., Ltd.",0003,房地产,J,房地产业,K70,...,A,None,2023-04-27,None,上海市,310000,上海市,310000,私营企业,P0306

In [22]:
sea_lst = []
for y in range(1990, 2024):
    for s in ['03-31', '06-30', '09-30', '12-31']:
        sea_lst.append(f'{y}-{s}')
sea_df = pd.DataFrame(sea_lst[:-3], columns=['会计期间'])
stk_df = pd.read_csv('../../data/csmar/公司文件.csv')
stk_df['on'] = 0
sea_df['on'] = 0
header = pd.merge(stk_df, sea_df, on=['on'], how='left')[['证券代码', '会计期间']]
header

          证券代码        会计期间
0            1  1990-03-31
1            1  1990-06-30
2            1  1990-09-30
3            1  1990-12-31
4            1  1991-03-31
...        ...         ...
728835  900957  2022-03-31
728836  900957  2022-06-30
728837  900957  2022-09-30
728838  900957  2022-12-31
728839  900957  2023-03-31

[728840 rows x 2 columns]

In [65]:
# 资产负债表 — 资产负债表
# 本表数据总记录数：551703条，数据频率：季度，数据开始时间：1990-12-31，数据结束时间：2023-03-31

df_list = []
for month in ['03', '06', '09', '12']:
    data1 = csmar.query(['Stkcd', 'ShortName', 'Accper', 'Typrep', 'IfCorrect', 'DeclareDate', 'A001101000', 'A0d1101101', 'A0d1102000', 'A0d1102101', 'A0b1103000', 'A0b1104000', 'A0b1105000', 'A0f1106000', 'A001107000', 'A0f1108000', 'A001109000', 'A001110000', 'A001111000', 'A001127000', 'A001112000', 'A0i1113000', 'A0i1114000', 'A0i1115000', 'A0i1116000', 'A0i1116101', 'A0i1116201', 'A0i1116301', 'A0i1116401', 'A001119000', 'A001120000', 'A001121000', 'A0f1122000', 'A001123000', 'A001128000', 'A001124000', 'A0d1126000', 'A001125000', 'A001100000', 'A0i1224000', 'A0i1225000', 'A0b1201000', 'A001226000', 'A001202000', 'A001227000', 'A001203000', 'A001204000', 'A001205000', 'A001228000', 'A001229000', 'A001206000', 'A001207000', 'A0i1209000', 'A0i1210000', 'A001211000', 'A001212000', 'A001213000', 'A001214000', 'A001215000', 'A001216000', 'A001217000', 'A001230000', 'A001218000', 'A0d1218101', 'A001219000', 'A001220000', 'A001221000', 'A001222000', 'A0F1224000', 'A001223000', 'A001200000', 'A0f1300000', 'A001000000', 'A002101000', 'A0d2101101', 'A0b2102000', 'A0b2103000', 'A0b2103101', 'A0b2103201', 'A0f2104000', 'A002105000', 'A0f2106000', 'A002107000', 'A002108000', 'A002109000', 'A002128000', 'A0f2110000', 'A0i2111000', 'A002112000', 'A002113000', 'A002114000', 'A002115000', 'A0i2116000', 'A0i2117000', 'A0i2118000', 'A0i2119000', 'A0i2119101', 'A0i2119201', 'A0i2119301', 'A0i2119401', 'A002120000', 'A0i2121000', 'A0d2122000', 'A0d2123000', 'A0i2124000', 'A002125000', 'A002126000', 'A002127000', 'A002100000', 'A002201000', 'A0d2202000', 'A002203000', 'A002211000', 'A002204000', 'A002205000', 'A002206000', 'A002207000', 'A0F2210000', 'A002208000', 'A002209000', 'A002210000', 'A002200000', 'A0f2300000', 'A002000000', 'A003101000', 'A003112000', 'A003112101', 'A003112201', 'A003112301', 'A003102000', 'A003102101', 'A003103000', 'A0f3104000', 'A003105000', 'A003106000', 'A003107000', 'A0F3108000', 'A0F3109000', 'A003111000', 'A003100000', 'A003200000', 'A003000000', 'A004000000'],
                        f'Accper LIKE \'%____-{month}-__%\' AND Typrep = \'A\'', 'FS_Combas', start, end)
    df1 = pd.DataFrame(data1)
    df1.rename({'Stkcd': '证券代码', 'ShortName': '证券简称', 'Accper': '会计期间', 'Typrep': '报表类型', 'IfCorrect': '是否发生差错更正', 'DeclareDate': '差错更正披露日期', 'A001101000': '货币资金', 'A0d1101101': '其中:客户资金存款', 'A0d1102000': '结算备付金', 'A0d1102101': '其中：客户备付金', 'A0b1103000': '现金及存放中央银行款项', 'A0b1104000': '存放同业款项', 'A0b1105000': '贵金属', 'A0f1106000': '拆出资金净额', 'A001107000': '交易性金融资产', 'A0f1108000': '衍生金融资产', 'A001109000': '短期投资净额', 'A001110000': '应收票据净额', 'A001111000': '应收账款净额', 'A001127000': '应收款项融资', 'A001112000': '预付款项净额', 'A0i1113000': '应收保费净额', 'A0i1114000': '应收分保账款净额', 'A0i1115000': '应收代位追偿款净额', 'A0i1116000': '应收分保合同准备金净额', 'A0i1116101': '其中:应收分保未到期责任准备金净额', 'A0i1116201': '其中:应收分保未决赔款准备金净额', 'A0i1116301': '其中:应收分保寿险责任准备金净额', 'A0i1116401': '其中:应收分保长期健康险责任准备金净额', 'A001119000': '应收利息净额', 'A001120000': '应收股利净额', 'A001121000': '其他应收款净额', 'A0f1122000': '买入返售金融资产净额', 'A001123000': '存货净额', 'A001128000': '合同资产', 'A001124000': '一年内到期的非流动资产', 'A0d1126000': '存出保证金', 'A001125000': '其他流动资产', 'A001100000': '流动资产合计', 'A0i1224000': '保户质押贷款净额', 'A0i1225000': '定期存款', 'A0b1201000': '发放贷款及垫款净额', 'A001226000': '债权投资', 'A001202000': '可供出售金融资产净额', 'A001227000': '其他债权投资', 'A001203000': '持有至到期投资净额', 'A001204000': '长期应收款净额', 'A001205000': '长期股权投资净额', 'A001228000': '其他权益工具投资', 'A001229000': '其他非流动金融资产', 'A001206000': '长期债权投资净额', 'A001207000': '长期投资净额', 'A0i1209000': '存出资本保证金', 'A0i1210000': '独立账户资产', 'A001211000': '投资性房地产净额', 'A001212000': '固定资产净额', 'A001213000': '在建工程净额', 'A001214000': '工程物资', 'A001215000': '固定资产清理', 'A001216000': '生产性生物资产净额', 'A001217000': '油气资产净额', 'A001230000': '使用权资产', 'A001218000': '无形资产净额', 'A0d1218101': '其中:交易席位费', 'A001219000': '开发支出', 'A001220000': '商誉净额', 'A001221000': '长期待摊费用', 'A001222000': '递延所得税资产', 'A0F1224000': '代理业务资产', 'A001223000': '其他非流动资产', 'A001200000': '非流动资产合计', 'A0f1300000': '其他资产', 'A001000000': '资产总计', 'A002101000': '短期借款', 'A0d2101101': '其中:质押借款', 'A0b2102000': '向中央银行借款', 'A0b2103000': '吸收存款及同业存放', 'A0b2103101': '其中：同业及其他金融机构存放款项', 'A0b2103201': '其中：吸收存款', 'A0f2104000': '拆入资金', 'A002105000': '交易性金融负债', 'A0f2106000': '衍生金融负债', 'A002107000': '应付票据', 'A002108000': '应付账款', 'A002109000': '预收款项', 'A002128000': '合同负债', 'A0f2110000': '卖出回购金融资产款', 'A0i2111000': '应付手续费及佣金', 'A002112000': '应付职工薪酬', 'A002113000': '应交税费', 'A002114000': '应付利息', 'A002115000': '应付股利', 'A0i2116000': '应付赔付款', 'A0i2117000': '应付保单红利', 'A0i2118000': '保户储金及投资款', 'A0i2119000': '保险合同准备金', 'A0i2119101': '其中:未到期责任准备金', 'A0i2119201': '其中:未决赔款准备金', 'A0i2119301': '其中:寿险责任准备金', 'A0i2119401': '其中:长期健康险责任准备金', 'A002120000': '其他应付款', 'A0i2121000': '应付分保账款', 'A0d2122000': '代理买卖证券款', 'A0d2123000': '代理承销证券款', 'A0i2124000': '预收保费', 'A002125000': '一年内到期的非流动负债', 'A002126000': '其他流动负债', 'A002127000': '递延收益-流动负债', 'A002100000': '流动负债合计', 'A002201000': '长期借款', 'A0d2202000': '独立账户负债', 'A002203000': '应付债券', 'A002211000': '租赁负债', 'A002204000': '长期应付款', 'A002205000': '专项应付款', 'A002206000': '长期负债合计', 'A002207000': '预计负债', 'A0F2210000': '代理业务负债', 'A002208000': '递延所得税负债', 'A002209000': '其他非流动负债', 'A002210000': '递延收益-非流动负债', 'A002200000': '非流动负债合计', 'A0f2300000': '其他负债', 'A002000000': '负债合计', 'A003101000': '实收资本(或股本)', 'A003112000': '其他权益工具', 'A003112101': '其中：优先股', 'A003112201': '其中：永续债', 'A003112301': '其中：其他', 'A003102000': '资本公积', 'A003102101': '其中：库存股', 'A003103000': '盈余公积', 'A0f3104000': '一般风险准备', 'A003105000': '未分配利润', 'A003106000': '外币报表折算差额', 'A003107000': '加：未确认的投资损失', 'A0F3108000': '交易风险准备', 'A0F3109000': '专项储备', 'A003111000': '其他综合收益', 'A003100000': '归属于母公司所有者权益合计', 'A003200000': '少数股东权益', 'A003000000': '所有者权益合计', 'A004000000': '负债与所有者权益总计'}, 
               axis='columns', inplace=True)
    df_list.append(df1)

df2 = pd.concat(df_list)
df2['证券代码'] = df2['证券代码'].astype('int')
df3 = pd.merge(header, df2, on=['证券代码', '会计期间'], how='left')
df3['查询成功'] = 1
df3['查询成功'][df3['报表类型'].isna()] = 0
df3.to_csv('../../data/csmar/季_资产负债表.csv', index=False, encoding='utf-8-sig')
df3

,证券代码,会计期间,报表类型,货币资金,其中:客户资金存款,结算备付金,其中：客户备付金,现金及存放中央银行款项,存放同业款项,贵金属,...,其他非流动金融资产,合同负债,使用权资产,租赁负债,是否发生差错更正,差错更正披露日期,证券简称,代理业务资产,代理业务负债,查询成功
0,1,1990-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,1990-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,1,1990-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,1,1990-12-31,A,8.042000e+08,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,None,深发展A,NaN,NaN,1
4,1,1991-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728835,900957,2022-03-31,A,1.685958e+06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1091551.06,529245.6,0.0,None,凌云B股,NaN,NaN,1
728836,900957,2022-06-30,A,7.950567e+05,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,914736.13,529245.6,0.0,None,凌云B股,NaN,NaN,1
728837,900957,2022-09-30,A,2.139934e+06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,737921.20,529245.6,0.0,None,凌云B股,NaN,NaN,1
728838,900957,2022-12-31,A,4.120921e+07,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,561106.27,NaN,0.0,None,凌云B股,NaN,NaN,1
728839,900957,2023-03-31,A,4.667469e+07,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,384291.34,NaN,0.0,None,凌云B股,NaN,NaN,1

In [71]:
# 利润表 — 利润表
# 本表数据总记录数：553302条，数据频率：季度，数据开始时间：1990-12-31，数据结束时间：2023-03-31
# 注意：该表为累积表，指标由当年1月至统计截止日期计算

df_list = []
for month in ['03', '06', '09', '12']:
    data1 = csmar.query(['Stkcd', 'ShortName', 'Accper', 'Typrep', 'IfCorrect', 'DeclareDate', 'B001100000', 'B001101000', 'Bbd1102000', 'Bbd1102101', 'Bbd1102203', 'B0i1103000', 'B0i1103101', 'B0i1103111', 'B0i1103203', 'B0i1103303', 'B0d1104000', 'B0d1104101', 'B0d1104201', 'B0d1104301', 'B0d1104401', 'B0d1104501', 'B0f1105000', 'B001200000', 'B001201000', 'B0i1202000', 'B0i1203000', 'B0i1203101', 'B0i1203203', 'B0i1204000', 'B0i1204101', 'B0i1204203', 'B0i1205000', 'B0i1206000', 'B001207000', 'B0f1208000', 'B0i1208103', 'B0I1214000', 'B001209000', 'B001210000', 'B001216000', 'B001211000', 'B001211101', 'B001211203', 'B001305000', 'B001302000', 'B001302101', 'B001302201', 'B001303000', 'B001306000', 'B001301000', 'B001212000', 'B001307000', 'B001308000', 'B0f1213000', 'B001304000', 'B001300000', 'B001400000', 'B001400101', 'B001500000', 'B001500101', 'B001500201', 'B001000000', 'B002100000', 'B002200000', 'B002300000', 'B002000000', 'B002000101', 'B002000301', 'B002000201', 'B003000000', 'B004000000', 'B005000000', 'B006000000', 'B006000101', 'B006000103', 'B006000102'], 
                        f'Accper LIKE \'%____-{month}-__%\' AND Typrep = \'A\'', 'FS_Comins', start, end)
    df1 = pd.DataFrame(data1)
    df1.rename({'Stkcd': '证券代码', 'ShortName': '证券简称', 'Accper': '会计期间', 'Typrep': '报表类型', 'IfCorrect': '是否发生差错更正', 'DeclareDate': '差错更正披露日期', 'B001100000': '营业总收入', 'B001101000': '营业收入', 'Bbd1102000': '利息净收入', 'Bbd1102101': '利息收入', 'Bbd1102203': '利息支出', 'B0i1103000': '已赚保费', 'B0i1103101': '保险业务收入', 'B0i1103111': '其中：分保费收入', 'B0i1103203': '减：分出保费', 'B0i1103303': '减：提取未到期责任准备金', 'B0d1104000': '手续费及佣金净收入', 'B0d1104101': '其中：代理买卖证券业务净收入', 'B0d1104201': '其中:证券承销业务净收入', 'B0d1104301': '其中：受托客户资产管理业务净收入', 'B0d1104401': '手续费及佣金收入', 'B0d1104501': '手续费及佣金支出', 'B0f1105000': '其他业务收入', 'B001200000': '营业总成本', 'B001201000': '营业成本', 'B0i1202000': '退保金', 'B0i1203000': '赔付支出净额', 'B0i1203101': '赔付支出', 'B0i1203203': '减：摊回赔付支出', 'B0i1204000': '提取保险责任准备金净额', 'B0i1204101': '提取保险责任准备金', 'B0i1204203': '减：摊回保险责任准备金', 'B0i1205000': '保单红利支出', 'B0i1206000': '分保费用', 'B001207000': '税金及附加', 'B0f1208000': '业务及管理费', 'B0i1208103': '减：摊回分保费用', 'B0I1214000': '保险业务手续费及佣金支出', 'B001209000': '销售费用', 'B001210000': '管理费用', 'B001216000': '研发费用', 'B001211000': '财务费用', 'B001211101': '其中：利息费用(财务费用)', 'B001211203': '其中：利息收入(财务费用)', 'B001305000': '其他收益', 'B001302000': '投资收益', 'B001302101': '其中：对联营企业和合营企业的投资收益', 'B001302201': '其中：以摊余成本计量的金融资产终止确认收益', 'B001303000': '汇兑收益', 'B001306000': '净敞口套期收益', 'B001301000': '公允价值变动收益', 'B001212000': '资产减值损失', 'B001307000': '信用减值损失', 'B001308000': '资产处置收益', 'B0f1213000': '其他业务成本', 'B001304000': '其他业务利润', 'B001300000': '营业利润', 'B001400000': '加：营业外收入', 'B001400101': '其中：非流动资产处置利得', 'B001500000': '减：营业外支出', 'B001500101': '其中：非流动资产处置净损益', 'B001500201': '其中：非流动资产处置损失', 'B001000000': '利润总额', 'B002100000': '减：所得税费用', 'B002200000': '未确认的投资损失', 'B002300000': '影响净利润的其他项目', 'B002000000': '净利润', 'B002000101': '归属于母公司所有者的净利润', 'B002000301': '归属于母公司其他权益工具持有者的净利润', 'B002000201': '少数股东损益', 'B003000000': '基本每股收益', 'B004000000': '稀释每股收益', 'B005000000': '其他综合收益(损失)', 'B006000000': '综合收益总额', 'B006000101': '归属于母公司所有者的综合收益', 'B006000103': '归属于母公司其他权益工具持有者的综合收益总额', 'B006000102': '归属少数股东的综合收益'}, 
               axis='columns', inplace=True)
    df_list.append(df1)

df2 = pd.concat(df_list)
df2['证券代码'] = df2['证券代码'].astype('int')
df3 = pd.merge(header, df2, on=['证券代码','会计期间'], how='left')
df3['查询成功'] = 1
df3['查询成功'][df3['报表类型'].isna()] = 0
df3.to_csv('../../data/csmar/季_利润表.csv', index=False, encoding='utf-8-sig')
df3

,证券代码,会计期间,报表类型,营业总收入,营业收入,利息净收入,利息收入,利息支出,已赚保费,保险业务收入,...,净敞口套期收益,信用减值损失,资产处置收益,归属于母公司其他权益工具持有者的净利润,是否发生差错更正,差错更正披露日期,证券简称,保险业务手续费及佣金支出,归属于母公司其他权益工具持有者的综合收益总额,查询成功
0,1,1990-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,1990-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,1,1990-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,1,1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,1,1991-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728835,900957,2022-03-31,A,2.930621e+07,2.930621e+07,NaN,NaN,NaN,NaN,NaN,...,NaN,-4526526.44,NaN,NaN,0.0,None,凌云B股,NaN,NaN,1
728836,900957,2022-06-30,A,6.468960e+07,6.468960e+07,NaN,NaN,NaN,NaN,NaN,...,NaN,-6673514.12,NaN,NaN,0.0,None,凌云B股,NaN,NaN,1
728837,900957,2022-09-30,A,9.451148e+07,9.451148e+07,NaN,NaN,NaN,NaN,NaN,...,NaN,-9005559.31,NaN,NaN,0.0,None,凌云B股,NaN,NaN,1
728838,900957,2022-12-31,A,1.199133e+08,1.199133e+08,NaN,NaN,NaN,NaN,NaN,...,NaN,2640770.45,NaN,NaN,0.0,None,凌云B股,NaN,NaN,1
728839,900957,2023-03-31,A,3.054123e+07,3.054123e+07,NaN,NaN,NaN,NaN,NaN,...,NaN,-2824443.30,NaN,NaN,0.0,None,凌云B股,NaN,NaN,1

In [105]:
# 现金流量表 — 现金流量表(直接法)
# 本表数据总记录数：528649条，数据频率：季度，数据开始时间：1997-06-30，数据结束时间：2023-03-31
# 注意：该表为累积表，指标由当年1月至统计截止日期计算

df_list = []
for month in ['03', '06', '09', '12']:
    data1 = csmar.query(['Stkcd', 'ShortName', 'Accper', 'Typrep', 'IfCorrect', 'DeclareDate', 'C001001000', 'C0b1002000', 'C0F1023000', 'C0b1003000', 'C0b1004000', 'C0i1005000', 'C0i1006000', 'C0i1007000', 'C0d1008000', 'C0f1009000', 'C0d1010000', 'C0d1011000', 'C0F1024000', 'C0F1025000', 'C001012000', 'C001013000', 'C001100000', 'C001014000', 'C0b1015000', 'C0F1026000', 'C0b1016000', 'C0i1017000', 'C0f1018000', 'C0F1027000', 'C0F1028000', 'C0F1029000', 'C0F1030000', 'C0F1031000', 'C0F1032000', 'C0i1019000', 'C001020000', 'C001021000', 'C001022000', 'C001200000', 'C001000000', 'C002001000', 'C002002000', 'C002003000', 'C002004000', 'C002005000', 'C002100000', 'C002006000', 'C002007000', 'C0i2008000', 'C002009000', 'C002010000', 'C002200000', 'C002000000', 'C003008000', 'C003001000', 'C003001101', 'C003003000', 'C003002000', 'C003004000', 'C003100000', 'C003005000', 'C003006000', 'C003006101', 'C003007000', 'C003200000', 'C003000000', 'C004000000', 'C007000000', 'C005000000', 'C005001000', 'C006000000'], 
                        f'Accper LIKE \'%____-{month}-__%\' AND Typrep = \'A\'', 'FS_Comscfd', start, end)
    df1 = pd.DataFrame(data1)
    df1.rename({'Stkcd': '证券代码', 'ShortName': '证券简称', 'Accper': '会计期间', 'Typrep': '报表类型', 'IfCorrect': '是否发生差错更正', 'DeclareDate': '差错更正披露日期', 'C001001000': '销售商品、提供劳务收到的现金', 'C0b1002000': '客户存款和同业存放款项净增加额', 'C0F1023000': '存放央行和同业款项净减少额', 'C0b1003000': '向中央银行借款净增加额', 'C0b1004000': '向其他金融机构拆入资金净增加额', 'C0i1005000': '收到原保险合同保费取得的现金', 'C0i1006000': '收到再保险业务现金净额', 'C0i1007000': '保户储金及投资款净增加额', 'C0d1008000': '处置交易性金融资产净增加额', 'C0f1009000': '收取利息、手续费及佣金的现金', 'C0d1010000': '拆入资金净增加额', 'C0d1011000': '回购业务资金净增加额', 'C0F1024000': '拆出资金净减少额', 'C0F1025000': '买入返售款项净减少额', 'C001012000': '收到的税费返还', 'C001013000': '收到的其他与经营活动有关的现金', 'C001100000': '经营活动现金流入小计', 'C001014000': '购买商品、接受劳务支付的现金', 'C0b1015000': '客户贷款及垫款净增加额', 'C0F1026000': '向中央银行借款净减少额', 'C0b1016000': '存放中央银行和同业款项净增加额', 'C0i1017000': '支付原保险合同赔付款项的现金', 'C0f1018000': '支付利息、手续费及佣金的现金', 'C0F1027000': '支付再保业务现金净额', 'C0F1028000': '保户储金及投资款净减少额', 'C0F1029000': '拆出资金净增加额', 'C0F1030000': '买入返售款项净增加额', 'C0F1031000': '拆入资金净减少额', 'C0F1032000': '卖出回购款项净减少额', 'C0i1019000': '支付保单红利的现金', 'C001020000': '支付给职工以及为职工支付的现金', 'C001021000': '支付的各项税费', 'C001022000': '支付其他与经营活动有关的现金', 'C001200000': '经营活动现金流出小计', 'C001000000': '经营活动产生的现金流量净额', 'C002001000': '收回投资收到的现金', 'C002002000': '取得投资收益收到的现金', 'C002003000': '处置固定资产、无形资产和其他长期资产收回的现金净额', 'C002004000': '处置子公司及其他营业单位收到的现金净额', 'C002005000': '收到的其他与投资活动有关的现金', 'C002100000': '投资活动产生的现金流入小计', 'C002006000': '购建固定资产、无形资产和其他长期资产支付的现金', 'C002007000': '投资支付的现金', 'C0i2008000': '质押贷款净增加额', 'C002009000': '取得子公司及其他营业单位支付的现金净额', 'C002010000': '支付其他与投资活动有关的现金', 'C002200000': '投资活动产生的现金流出小计', 'C002000000': '投资活动产生的现金流量净额', 'C003008000': '吸收投资收到的现金', 'C003001000': '吸收权益性投资收到的现金', 'C003001101': '其中：子公司吸收少数股东投资收到的现金', 'C003003000': '发行债券收到的现金', 'C003002000': '取得借款收到的现金', 'C003004000': '收到其他与筹资活动有关的现金', 'C003100000': '筹资活动现金流入小计', 'C003005000': '偿还债务支付的现金', 'C003006000': '分配股利、利润或偿付利息支付的现金', 'C003006101': '其中：子公司支付给少数股东的股利、利润', 'C003007000': '支付其他与筹资活动有关的现金', 'C003200000': '筹资活动现金流出小计', 'C003000000': '筹资活动产生的现金流量净额', 'C004000000': '汇率变动对现金及现金等价物的影响', 'C007000000': '其他对现金的影响', 'C005000000': '现金及现金等价物净增加额', 'C005001000': '期初现金及现金等价物余额', 'C006000000': '期末现金及现金等价物余额'}, 
               axis='columns', inplace=True)
    df_list.append(df1)

df2 = pd.concat(df_list)
df2['证券代码'] = df2['证券代码'].astype('int')
df3 = pd.merge(header, df2, on=['证券代码','会计期间'], how='left')
df3['查询成功'] = 1
df3['查询成功'][df3['报表类型'].isna()] = 0
df3.to_csv('../../data/csmar/季_现金流量表(直接法).csv', index=False, encoding='utf-8-sig')
df3

,证券代码,会计期间,报表类型,销售商品、提供劳务收到的现金,客户存款和同业存放款项净增加额,向中央银行借款净增加额,向其他金融机构拆入资金净增加额,收到原保险合同保费取得的现金,收到再保险业务现金净额,保户储金及投资款净增加额,...,拆出资金净增加额,买入返售款项净增加额,拆入资金净减少额,卖出回购款项净减少额,经营活动现金流出小计,投资活动产生的现金流入小计,投资活动产生的现金流出小计,筹资活动现金流入小计,筹资活动现金流出小计,查询成功
0,1,1990-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,1990-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,1,1990-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,1,1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,1,1991-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728835,900957,2022-03-31,A,7.405485e+06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,9537553.98,21251629.91,12214200.00,NaN,6409337.41,1
728836,900957,2022-06-30,A,2.086331e+07,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,20006953.23,30612437.02,21969046.61,NaN,13968217.51,1
728837,900957,2022-09-30,A,4.676344e+07,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,82326510.95,44074433.90,39129632.61,25000000.0,45517531.59,1
728838,900957,2022-12-31,A,1.129156e+08,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,87703022.59,57645959.14,65857947.14,25000000.0,54156800.78,1
728839,900957,2023-03-31,A,8.425461e+06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,13377991.40,55784359.87,36932528.00,NaN,8625569.18,1

In [88]:
# 现金流量表 — 现金流量表(间接法)
# 本表数据总记录数：272792条，数据频率：季度，数据开始时间：1997-06-30，数据结束时间：2023-03-31
# 注意：该表为累积表，指标由当年1月至统计截止日期计算

df_list = []
for month in ['03', '06', '09', '12']:
    data1 = csmar.query(['Stkcd', 'ShortName', 'Accper', 'Typrep', 'IfCorrect', 'DeclareDate', 'D000101000', 'D000118000', 'D000117000', 'D000102000', 'D000103000', 'D000104000', 'D000105000', 'D000106000', 'D000107000', 'D000108000', 'D000109000', 'D000110000', 'D000111000', 'D000112000', 'D000113000', 'D000114000', 'D000115000', 'D000116000', 'D000100000', 'D000201000', 'D000202000', 'D000203000', 'D000204000', 'D000205000', 'D000206000', 'D000207000', 'D000200000'], 
                        f'Accper LIKE \'%____-{month}-__%\' AND Typrep = \'A\'', 'FS_Comscfi', start, end)
    df1 = pd.DataFrame(data1)
    df1.rename({'Stkcd': '证券代码', 'ShortName': '证券简称', 'Accper': '会计期间', 'Typrep': '报表类型', 'IfCorrect': '是否发生差错更正', 'DeclareDate': '差错更正披露日期', 'D000101000': '净利润', 'D000118000': '信用减值损失', 'D000117000': '未确认的投资损失', 'D000102000': '资产减值准备', 'D000103000': '固定资产折旧、油气资产折耗、生产性生物资产折旧', 'D000104000': '无形资产摊销', 'D000105000': '长期待摊费用摊销', 'D000106000': '处置固定资产、无形资产和其他长期资产的损失(收益以“－”号填列)', 'D000107000': '固定资产报废损失(收益以“－”号填列)', 'D000108000': '公允价值变动损失(收益以“－”号填列)', 'D000109000': '财务费用(收益以“－”号填列)', 'D000110000': '投资损失(收益以“－”号填列)', 'D000111000': '递延所得税资产减少(增加以“－”号填列)', 'D000112000': '递延所得税负债增加(减少以“－”号填列)', 'D000113000': '存货的减少(增加以“－”号填列)', 'D000114000': '经营性应收项目的减少(增加以“－”号填列)', 'D000115000': '经营性应付项目的增加(减少以“－”号填列)', 'D000116000': '其他', 'D000100000': '经营活动产生的现金流量净额', 'D000201000': '债务转为资本', 'D000202000': '一年内到期的可转换公司债券', 'D000203000': '融资租赁固定资产', 'D000204000': '现金的期末余额', 'D000205000': '现金的期初余额', 'D000206000': '现金等价物的期末余额', 'D000207000': '现金等价物的期初余额', 'D000200000': '现金及现金等价物净增加额'}, 
               axis='columns',inplace=True)
    df_list.append(df1)

df2 = pd.concat(df_list)
df2['证券代码'] = df2['证券代码'].astype('int')
df3 = pd.merge(header, df2, on=['证券代码','会计期间'], how='left')
df3['查询成功'] = 1
df3['查询成功'][df3['报表类型'].isna()] = 0
df3.to_csv('../../data/csmar/季_现金流量表(间接法).csv', index=False, encoding='utf-8-sig')
df3

,证券代码,会计期间,报表类型,净利润,未确认的投资损失,资产减值准备,固定资产折旧、油气资产折耗、生产性生物资产折旧,无形资产摊销,长期待摊费用摊销,处置固定资产、无形资产和其他长期资产的损失(收益以“－”号填列),...,现金的期末余额,现金的期初余额,现金等价物的期末余额,现金等价物的期初余额,现金及现金等价物净增加额,信用减值损失,是否发生差错更正,差错更正披露日期,证券简称,查询成功
0,1,1990-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,1990-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,1,1990-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,1,1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,1,1991-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728835,900957,2022-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
728836,900957,2022-06-30,A,22013665.53,NaN,NaN,17545158.44,142917.38,1645200.0,1026.9,...,277856.70,664667.78,NaN,NaN,-386811.08,6673514.12,0.0,None,凌云B股,1
728837,900957,2022-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
728838,900957,2022-12-31,A,40552488.12,NaN,NaN,35089478.88,287878.80,3193600.0,NaN,...,40692005.88,664667.78,NaN,NaN,40027338.10,-2640770.45,0.0,None,凌云B股,1
728839,900957,2023-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [96]:
# 相对价值指标 — 相对价值指标
# 本表数据总记录数：221984条，数据频率：季度，数据开始时间：1990-12-31，数据结束时间：2023-03-31

df_list = []
for month in ['03', '06', '09', '12']:
    data1 = csmar.query(['Stkcd', 'ShortName', 'Accper', 'Indcd', 'Indnme', 'Source', 'F100101B', 'F100102B', 'F100103C', 'F100201B', 'F100202B', 'F100203C', 'F100301B', 'F100302B', 'F100303C', 'F100401A', 'F100501A', 'F100601B', 'F100602B', 'F100603C', 'F100701A', 'F100801A', 'F100802A', 'F100901A', 'F100902A', 'F100903A', 'F100904A', 'F101001A', 'F101002A', 'F101101B', 'F101201B', 'F101202B', 'F101301B', 'F101302C'], 
                        f'Accper LIKE \'%____-{month}-__%\'', 'FI_T10', start, end)
    df1 = pd.DataFrame(data1)
    df1.rename({'Stkcd': '证券代码', 'ShortName': '证券简称', 'Accper': '会计期间', 'Indcd': '行业代码', 'Indnme': '行业名称', 'Source': '公告来源', 'F100101B': '市盈率（PE）1', 'F100102B': '市盈率（PE）2', 'F100103C': '市盈率（PE）TTM', 'F100201B': '市销率（PS）1', 'F100202B': '市销率（PS）2', 'F100203C': '市销率（PS）TTM', 'F100301B': '市现率（PCF）1', 'F100302B': '市现率（PCF）2', 'F100303C': '市现率（PCF）TTM', 'F100401A': '市净率（PB）', 'F100501A': '市值有形资产比', 'F100601B': '市盈率母公司（PE）1', 'F100602B': '市盈率母公司（PE）2', 'F100603C': '市盈率母公司（PE）TTM', 'F100701A': '市净率母公司（PB）', 'F100801A': '市值A', 'F100802A': '市值B', 'F100901A': '托宾Q值A', 'F100902A': '托宾Q值B', 'F100903A': '托宾Q值C', 'F100904A': '托宾Q值D', 'F101001A': '账面市值比A', 'F101002A': '账面市值比B', 'F101101B': '本利比', 'F101201B': '普通股获利率A', 'F101202B': '普通股获利率B', 'F101301B': '企业价值倍数', 'F101302C': '企业价值倍数TTM'}, 
               axis='columns', inplace=True)
    df_list.append(df1)

df2 = pd.concat(df_list)
df2['证券代码'] = df2['证券代码'].astype('int')
df3 = pd.merge(header, df2, on=['证券代码','会计期间'], how='left')
df3['查询成功'] = 1
df3['查询成功'][df3['行业代码'].isna()] = 0
df3.to_csv('../../data/csmar/季_相对价值指标.csv', index=False, encoding='utf-8-sig')
df3

,证券代码,会计期间,行业代码,市盈率（PE）1,市盈率（PE）2,市盈率（PE）TTM,市销率（PS）1,市销率（PS）2,市销率（PS）TTM,市现率（PCF）1,...,账面市值比B,本利比,普通股获利率A,普通股获利率B,企业价值倍数,企业价值倍数TTM,行业名称,公告来源,证券简称,查询成功
0,1,1990-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,1990-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,1,1990-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,1,1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,1,1991-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728835,900957,2022-03-31,K70,45.839894,40.744610,46.839842,11.207814,10.810664,11.068807,58.762405,...,0.885201,None,0.0,-0.097412,97.284271,25.256926,房地产业,0.0,凌云B股,1
728836,900957,2022-06-30,K70,50.665377,31.813934,40.312464,12.387641,10.826181,11.509324,64.948218,...,0.846133,None,0.0,-0.002399,26.780516,14.200073,房地产业,0.0,凌云B股,1
728837,900957,2022-09-30,K70,52.611561,36.053627,39.389068,12.863481,11.542140,11.967919,67.443042,...,0.833496,None,0.0,0.035922,29.220263,22.387634,房地产业,0.0,凌云B股,1
728838,900957,2022-12-31,K70,33.805176,33.805176,33.805176,11.432296,11.432296,11.432296,17.712567,...,0.872507,None,0.0,-0.023622,13.259632,13.259632,房地产业,0.0,凌云B股,1
728839,900957,2023-03-31,K70,31.166119,36.234080,30.456839,10.539815,10.345552,10.432369,16.329806,...,0.921870,None,0.0,-0.078067,93.431179,19.216310,房地产业,0.0,凌云B股,1

In [20]:
# 个股交易数据 — 日个股回报率文件
# 本表数据总记录数：14422922条，数据频率：日度，数据开始时间：1990-12-19，数据结束时间：2023-05-01

data1 = csmar.query(['Stkcd', 'Trddt', 'Opnprc', 'Hiprc', 'Loprc', 'Clsprc', 'Dnshrtrd', 'Dnvaltrd', 'Dsmvosd', 'Dsmvtll', 'Dretwd', 'Dretnd', 'Adjprcwd', 'Adjprcnd', 'Markettype', 'Capchgdt', 'Trdsta', 'Ahshrtrd_D', 'Ahvaltrd_D', 'PreClosePrice', 'ChangeRatio'], 
                    f'Trddt LIKE \'%____-__-__%\'', 'TRD_Dalyr', start, end)
df1 = pd.DataFrame(data1)
df1.rename({'Stkcd':'证券代码', 'Trddt':'交易日期', 'Opnprc':'日开盘价', 'Hiprc':'日最高价', 'Loprc':'日最低价', 'Clsprc':'日收盘价', 'Dnshrtrd':'日个股交易股数', 'Dnvaltrd':'日个股交易金额', 'Dsmvosd':'日个股流通市值', 'Dsmvtll':'日个股总市值', 'Dretwd':'考虑现金红利再投资的日个股回报率', 'Dretnd':'不考虑现金红利的日个股回报率', 'Adjprcwd':'考虑现金红利再投资的收盘价的可比价格', 'Adjprcnd':'不考虑现金红利的收盘价的可比价格', 'Markettype':'市场类型', 'Capchgdt':'最新股本变动日期', 'Trdsta':'交易状态', 'Ahshrtrd_D':'日盘后成交总量', 'Ahvaltrd_D':'日盘后成交总额', 'PreClosePrice':'昨收盘(交易所)', 'ChangeRatio':'涨跌幅'}, 
            axis='columns', inplace=True)
df1['证券代码'] = df1['证券代码'].astype('int')
df1.to_csv('../../data/csmar/日_日个股回报率文件.csv', index=False, encoding='utf-8-sig')
df1

,证券代码,交易日期,日开盘价,日最高价,日最低价,日收盘价,日个股交易股数,日个股交易金额,日个股流通市值,日个股总市值,...,不考虑现金红利的日个股回报率,考虑现金红利再投资的收盘价的可比价格,不考虑现金红利的收盘价的可比价格,市场类型,最新股本变动日期,交易状态,日盘后成交总量,日盘后成交总额,昨收盘(交易所),涨跌幅
0,1,1991-04-03,49.000,49.000,49.000,49.000,100,5000.0,1298500.0,2376508.38,...,0.225000,49.000000,49.000000,4,1991-04-03,1,0.0,0.0,0.000,0.000000
1,1,1991-04-04,48.760,48.760,48.760,48.760,300,15000.0,1292140.0,2364868.34,...,-0.004898,48.760000,48.760000,4,1991-04-03,1,0.0,0.0,49.000,-0.004898
2,1,1991-04-05,48.520,48.520,48.520,48.520,200,10000.0,1285780.0,2353228.30,...,-0.004922,48.520000,48.520000,4,1991-04-03,1,0.0,0.0,48.760,-0.004922
3,1,1991-04-06,48.280,48.280,48.280,48.280,700,34000.0,1279420.0,2341588.26,...,-0.004946,48.280000,48.280000,4,1991-04-03,1,0.0,0.0,48.520,-0.004946
4,1,1991-04-08,48.040,48.040,48.040,48.040,200,10000.0,1273060.0,2329948.21,...,-0.004971,48.040000,48.040000,4,1991-04-03,1,0.0,0.0,48.280,-0.004971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73120,900957,2023-04-24,0.509,0.509,0.501,0.504,89100,44854.0,92736.0,175896.00,...,-0.001980,0.507988,0.503999,2,2000-08-03,1,0.0,0.0,0.505,-0.001980
78357,900957,2023-04-25,0.500,0.515,0.500,0.510,179557,90884.0,93840.0,177990.00,...,0.011905,0.514035,0.509999,2,2000-08-03,1,0.0,0.0,0.504,0.011905
83596,900957,2023-04-26,0.510,0.515,0.510,0.511,139357,71516.0,94024.0,178339.00,...,0.001961,0.515043,0.510999,2,2000-08-03,1,0.0,0.0,0.510,0.001961
88833,900957,2023-04-27,0.515,0.520,0.511,0.520,142800,73944.0,95680.0,181480.00,...,0.017613,0.524114,0.519999,2,2000-08-03,1,0.0,0.0,0.511,0.017613
94136,900957,2023-04-28,0.517,0.525,0.517,0.525,124100,64496.0,96600.0,183225.00,...,0.009615,0.529154,0.524999,2,2000-08-03,1,0.0,0.0,0.520,0.009615

In [6]:
# 个股交易数据 — 日个股回报率文件
# 本表数据总记录数：14522414 条，数据频率：日度，数据开始时间： 1990-12-19，数据结束时间： 2023-06-01

data1 = csmar.query(['Stkcd', 'Trddt', 'Opnprc', 'Hiprc', 'Loprc', 'Clsprc', 'Dnshrtrd', 'Dnvaltrd', 'Dsmvosd', 'Dsmvtll', 'Dretwd', 'Dretnd', 'Adjprcwd', 'Adjprcnd', 'Markettype', 'Capchgdt', 'Trdsta', 'Ahshrtrd_D', 'Ahvaltrd_D', 'PreClosePrice', 'ChangeRatio'], 
                    f'Trddt LIKE \'%____-__-__%\'', 'TRD_Dalyr', start, end)
df1 = pd.DataFrame(data1)
df1.rename({'Stkcd':'证券代码', 'Trddt':'交易日期', 'Opnprc':'日开盘价', 'Hiprc':'日最高价', 'Loprc':'日最低价', 'Clsprc':'日收盘价', 'Dnshrtrd':'日个股交易股数', 'Dnvaltrd':'日个股交易金额', 'Dsmvosd':'日个股流通市值', 'Dsmvtll':'日个股总市值', 'Dretwd':'考虑现金红利再投资的日个股回报率', 'Dretnd':'不考虑现金红利的日个股回报率', 'Adjprcwd':'考虑现金红利再投资的收盘价的可比价格', 'Adjprcnd':'不考虑现金红利的收盘价的可比价格', 'Markettype':'市场类型', 'Capchgdt':'最新股本变动日期', 'Trdsta':'交易状态', 'Ahshrtrd_D':'日盘后成交总量', 'Ahvaltrd_D':'日盘后成交总额', 'PreClosePrice':'昨收盘(交易所)', 'ChangeRatio':'涨跌幅'}, 
            axis='columns', inplace=True)
df1['证券代码'] = df1['证券代码'].astype('int')
df1.to_csv('../../data/csmar/日_日个股回报率文件.csv', index=False, encoding='utf-8-sig')
df1

,证券代码,交易日期,日开盘价,日最高价,日最低价,日收盘价,日个股交易股数,日个股交易金额,日个股流通市值,日个股总市值,...,不考虑现金红利的日个股回报率,考虑现金红利再投资的收盘价的可比价格,不考虑现金红利的收盘价的可比价格,市场类型,最新股本变动日期,交易状态,日盘后成交总量,日盘后成交总额,昨收盘(交易所),涨跌幅
0,1,1991-04-03,49.000,49.000,49.000,49.000,100,5000.0,1298500.00,2376508.38,...,0.225000,49.000000,49.000000,4,1991-04-03,1,0.0,0.0,0.000,0.000000
1,1,1991-04-04,48.760,48.760,48.760,48.760,300,15000.0,1292140.00,2364868.34,...,-0.004898,48.760000,48.760000,4,1991-04-03,1,0.0,0.0,49.000,-0.004898
2,1,1991-04-05,48.520,48.520,48.520,48.520,200,10000.0,1285780.00,2353228.30,...,-0.004922,48.520000,48.520000,4,1991-04-03,1,0.0,0.0,48.760,-0.004922
3,1,1991-04-06,48.280,48.280,48.280,48.280,700,34000.0,1279420.00,2341588.26,...,-0.004946,48.280000,48.280000,4,1991-04-03,1,0.0,0.0,48.520,-0.004946
4,1,1991-04-08,48.040,48.040,48.040,48.040,200,10000.0,1273060.00,2329948.21,...,-0.004971,48.040000,48.040000,4,1991-04-03,1,0.0,0.0,48.280,-0.004971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109885,900947,2023-06-01,0.245,0.247,0.243,0.244,504080,123257.0,474910.82,474910.82,...,0.004115,3.613256,2.512206,2,2018-08-13,1,0.0,0.0,0.243,0.004115
109886,900948,2023-06-01,1.299,1.315,1.289,1.305,3483227,4547075.0,1733040.00,4246479.14,...,0.011628,24.014398,10.439851,2,2013-07-16,1,0.0,0.0,1.290,0.011628
109887,900952,2023-06-01,0.241,0.244,0.236,0.241,202249,48404.0,53696.48,53696.48,...,-0.008230,0.551977,0.483751,2,2019-07-30,1,0.0,0.0,0.243,-0.008230
109888,900953,2023-06-01,0.378,0.382,0.368,0.373,412909,154561.0,89520.00,238720.00,...,-0.002674,0.384377,0.373000,2,2013-12-31,1,0.0,0.0,0.374,-0.002674
109889,900957,2023-06-01,0.506,0.509,0.500,0.503,224350,112697.0,92552.00,175547.00,...,-0.011788,0.506979,0.502999,2,2000-08-03,1,0.0,0.0,0.509,-0.011788

In [ ]:
# 公司事件 — 公司公告事件表
# 本表数据总记录数：5464846条，数据频率：日度，数据开始时间：2002-03-22，数据结束时间：2023-05-01

data1 = csmar.query(['AnnouncementID', 'Symbol', 'ShortName', 'DeclareDate', 'FullName', 'Title', 'ClassID', 'ClassName', 'ClassifyID', 'ClassifyName', 'FileSize', 'IndustryCode', 'IndustryName', 'AreaCode', 'Area'], 
                    f'DeclareDate LIKE \'%____-__-__%\'', 'ER_Announcement', start, end)
df1 = pd.DataFrame(data1)
df1.rename({'AnnouncementID': '公告ID', 'Symbol': '证券代码', 'ShortName': '证券简称', 'DeclareDate': '公告日期', 'FullName': '公司全称', 'Title': '公告标题', 'ClassID': '分类编码', 'ClassName': '分类', 'ClassifyID': '小类分类编码', 'ClassifyName': '小类分类', 'FileSize': '公告大小', 'IndustryCode': '行业代码', 'IndustryName': '行业', 'AreaCode': '地区代码', 'Area': '地区'}, 
           axis='columns', inplace=True)
df1['证券代码'] = df1['证券代码'].astype('int')
df1.to_csv('../../data/csmar/日_公司公告事件表.csv', index=False, encoding='utf-8-sig')
df1

In [15]:
# 基本数据 — 治理综合信息文件
# 本表数据总记录数：57804条，数据频率：年度，数据开始时间：1999-12-31，数据结束时间：2022-12-31

data1 = csmar.query(['Stkcd', 'Reptdt', 'Annodt', 'Y0301b', 'Y0401b', 'Y0501b', 'Y0601b', 'Y0701b', 'ChairmanID', 'Y0801b', 'ChairmanHoldshares', 'ChairmanHoldsharesRatio', 'GeneralManagerID', 'Y0901b', 'ManagerHoldshares', 'ManagerHoldsharesRatio', 'Y1001b', 'Y1401b', 'Y1701a', 'Y1701b', 'Y1701c', 'Y1901b'], 
                    f'Reptdt LIKE \'%____-__-__%\'', 'CG_Ybasic', start, end)
df1 = pd.DataFrame(data1)
df1.rename({'Stkcd': '证券代码', 'Reptdt': '统计截止日期', 'Annodt': '公告日期', 'Y0301b': '股本结构是否变化', 'Y0401b': '股东总数', 'Y0501b': '前十大股东是否存在关联', 'Y0601b': '员工人数', 'Y0701b': '离退休职工人数', 'ChairmanID': '董事长人员ID', 'Y0801b': '董事长名称', 'ChairmanHoldshares': '董事长持股数量', 'ChairmanHoldsharesRatio': '董事长持股比例', 'GeneralManagerID': '总经理人员ID', 'Y0901b': '总经理名称', 'ManagerHoldshares': '总经理持股数量', 'ManagerHoldsharesRatio': '总经理持股比例', 'Y1001b': '董事长与总经理兼任情况', 'Y1401b': '年薪披露方式', 'Y1701a': '委员会设立总数', 'Y1701b': '其中：四委设立个数', 'Y1701c': '其中：其他委员会设立个数', 'Y1901b': '备注'}, 
           axis='columns', inplace=True)
df1['证券代码'] = df1['证券代码'].astype('int')
df2 = pd.merge(header[header['会计期间'].apply(lambda x: True if x[5:7] == '12' else False)].rename(columns={'会计期间':'统计截止日期'}), 
               df1, on=['证券代码', '统计截止日期'], how='left')
df2['查询成功'] = 1
df2['查询成功'][df2['公告日期'].isna()] = 0
df2.to_csv('../../data/csmar/年_治理综合信息文件.csv', index=False, encoding='utf-8-sig')
df2

,证券代码,统计截止日期,公告日期,股本结构是否变化,股东总数,前十大股东是否存在关联,员工人数,离退休职工人数,董事长名称,总经理名称,...,委员会设立总数,其中：四委设立个数,其中：其他委员会设立个数,董事长人员ID,总经理人员ID,董事长持股数量,董事长持股比例,总经理持股数量,总经理持股比例,查询成功
0,1,1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,1991-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,1,1992-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,1,1993-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,1,1994-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180835,900957,2018-12-31,2019-03-30,1.0,24833.0,3.0,75.0,0.0,于爱新,连爱勤,...,4.0,4.0,0.0,30187460.0,30187458.0,0.0,0.0,0.0,0.0,1
180836,900957,2019-12-31,2020-04-25,1.0,23928.0,3.0,78.0,0.0,于爱新,连爱勤,...,4.0,4.0,0.0,30187460.0,30187458.0,0.0,0.0,0.0,0.0,1
180837,900957,2020-12-31,2021-04-09,1.0,23191.0,3.0,78.0,2.0,于爱新,连爱勤,...,4.0,4.0,0.0,30187460.0,30187458.0,0.0,0.0,0.0,0.0,1
180838,900957,2021-12-31,2022-04-20,1.0,22442.0,3.0,78.0,2.0,于爱新,连爱勤,...,4.0,4.0,0.0,30187460.0,30187458.0,0.0,0.0,0.0,0.0,1
180839,900957,2022-12-31,2023-04-08,1.0,21944.0,3.0,79.0,0.0,于爱新,连爱勤,...,4.0,4.0,0.0,30187460.0,30187458.0,0.0,0.0,0.0,0.0,1

In [5]:
# 基本数据 — 分配文件
# 本表数据总记录数：53457条，数据频率：日度，数据开始时间：1990-01-01，数据结束时间：2023-05-12

data1 = csmar.query(['Stkcd', 'Disttyp', 'Exdistdt', 'Annodt', 'Paydt', 'Amount', 'Roprc'], 
                    f'Exdistdt LIKE \'%____-__-__%\'', 'TRD_Cptl', start, end)
df1 = pd.DataFrame(data1)
df1.rename({'Stkcd': '证券代码', 'Disttyp': '分配类型', 'Exdistdt': '除权(息)日期', 'Annodt': '公告日期', 'Paydt': '支付日期', 'Amount': '分配比率', 'Roprc': '配股价格'}, 
           axis='columns', inplace=True)
df1['证券代码'] = df1['证券代码'].astype('int')
df1 = df1.sort_values(by=['证券代码', '除权(息)日期', '分配类型']).reset_index().drop(columns=['index'])
df1.to_csv('../../data/csmar/日_分配文件.csv', index=False, encoding='utf-8-sig')
df1

         证券代码 分配类型        公告日期     除权(息)日期        支付日期      分配比率    配股价格
0           1   RO  0000-00-00  1990-03-01  0000-00-00  0.100000   0.356
1           1   CA        None  1991-05-02        None  0.300000   0.000
2           1   SD        None  1991-05-02        None  0.400000   0.000
3           1   RO  0000-00-00  1991-08-01  1991-08-17  0.300000  12.000
4           1   CA  1992-03-14  1992-03-23  1992-03-23  0.200000   0.000
...       ...  ...         ...         ...         ...       ...     ...
53323  900956   CA  2019-05-07  2019-05-13  2019-05-22  0.100000   0.000
53324  900956   CA  2019-11-28  2019-12-04  2019-12-17  0.150000   0.000
53325  900957   CA  2001-05-12  2001-05-18  2001-05-23  0.019947   0.000
53326  900957   CA  2002-06-08  2002-06-12  2002-06-26  0.019997   0.000
53327  900957   CA  2003-07-23  2003-07-29  2003-08-13  0.010000   0.000

[53328 rows x 7 columns]

In [40]:
# 基本数据 — 股本变动文件
# 本表数据总记录数：105710条，数据频率：日度，数据开始时间：1990-12-10，数据结束时间：2023-05-12

data1 = csmar.query(['Stkcd', 'Shrchgdt', 'Shrtyp', 'Nshrttl', 'Nshrstt', 'Nshrlpd', 'Nshrlpf', 'Nshrlpn', 'Nshremp', 'Nshrmf', 'Nshrrot', 'Nshrprf', 'Nshra', 'Nshrb', 'Nshrh', 'Nshrunl', 'Nshrsms', 'Nshrglea', 'Nshrsina', 'Nshrlpo'], 
                    f'Shrchgdt LIKE \'%____-__-__%\'', 'TRD_Capchg', start, end)
df1 = pd.DataFrame(data1)
df1.rename({'Stkcd': '证券代码', 'Shrchgdt': '股本变动日期', 'Shrtyp': '股本变动类型', 'Nshrttl': '总股数', 'Nshrstt': '国有股股数', 'Nshrlpd': '境内法人股股数', 'Nshrlpf': '境外法人股股数', 'Nshrlpn': '募集法人股股数', 'Nshremp': '内部职工股股数', 'Nshrmf': '基金配售股数', 'Nshrrot': '转配股股数', 'Nshrprf': '优先股股数', 'Nshra': 'A股流通股数', 'Nshrb': 'B股流通股数', 'Nshrh': 'H股流通股数', 'Nshrunl': '流通配送股尚未流通股数', 'Nshrsms': '高管持股数', 'Nshrglea': '一般法人配售数', 'Nshrsina': '战略投资者配售数', 'Nshrlpo': '其他股股数'}, 
           axis='columns', inplace=True)
df1['证券代码'] = df1['证券代码'].astype('int')
df1 = df1.sort_values(by=['证券代码', '股本变动日期', '股本变动类型']).reset_index().drop(columns=['index'])
df1.to_csv('.././data/csmar/日_股本变动文件.csv', index=False, encoding='utf-8-sig')
df1

,证券代码,股本变动日期,股本变动类型,总股数,国有股股数,境内法人股股数,境外法人股股数,募集法人股股数,内部职工股股数,基金配售股数,转配股股数,优先股股数,A股流通股数,B股流通股数,H股流通股数,流通配送股尚未流通股数,高管持股数,一般法人配售数,战略投资者配售数,其他股股数
0,1,1991-04-03,10000,48500171.0,22000171.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,1991-08-01,00100,89751643.0,7787387.0,0.0,0.0,22309116.0,14666219.0,0.0,0.0,0.0,44988921.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,1992-03-23,03000,134696625.0,11687081.0,0.0,0.0,33480865.0,22010630.0,0.0,0.0,0.0,67518049.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,1993-05-24,03100,269417899.0,21620134.0,0.0,0.0,61939600.0,40719665.0,0.0,0.0,0.0,145138500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,1994-06-30,20008,269417899.0,21621080.0,0.0,0.0,61939568.0,6735000.0,0.0,0.0,0.0,179122251.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105578,900956,1999-07-15,10000,220000000.0,117600000.0,2400000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100000000.0,0.0,0.0,0.0,0.0,0.0,0.0
105579,900956,1999-08-13,00050,235000000.0,117600000.0,2400000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,115000000.0,0.0,0.0,0.0,0.0,0.0,0.0
105580,900956,2006-06-02,60000,235000000.0,117600000.0,2400000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,115000000.0,0.0,0.0,0.0,0.0,0.0,0.0
105581,900957,2000-07-28,10000,325000000.0,0.0,165000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,160000000.0,0.0,0.0,0.0,0.0,0.0,0.0
105582,900957,2000-08-03,00050,349000000.0,0.0,165000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,184000000.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
mon_lst = []
for y in range(1990, 2024):
    for m in ['01-31', '02-29' if (y % 4 == 0 and y % 100 != 0) or (y % 400 == 0) else '02-28', '03-31', '04-30', '05-31', '06-30', '07-31', '08-31', '09-30', '10-31', '11-30', '12-31']:
        mon_lst.append(f'{y}-{m}')
mon_df = pd.DataFrame(mon_lst[:-7], columns=['交易月份'])
mon_df['月份'] = mon_df['交易月份'].apply(lambda x: x[:7])
stk_df = pd.read_csv('../../data/csmar/公司文件.csv')
stk_df['on'] = 0
mon_df['on'] = 0
header = pd.merge(stk_df, mon_df, on=['on'], how='left')[['证券代码', '交易月份', '月份']]
header

           证券代码        交易月份       月份
0             1  1990-01-31  1990-01
1             1  1990-02-28  1990-02
2             1  1990-03-31  1990-03
3             1  1990-04-30  1990-04
4             1  1990-05-31  1990-05
...         ...         ...      ...
2197475  900957  2023-01-31  2023-01
2197476  900957  2023-02-28  2023-02
2197477  900957  2023-03-31  2023-03
2197478  900957  2023-04-30  2023-04
2197479  900957  2023-05-31  2023-05

[2197480 rows x 3 columns]

In [27]:
# 月频Beta文件 — 月收益Beta表（48个月滚动）
# 本表数据总记录数：482091 条，数据频率：月度，数据开始时间： 1994-12，数据结束时间： 2023-05

data1 = csmar.query(['Stkcd', 'Trdmnt', 'IsNotBSE', 'Betaval', 'Betavals', 'TradingMonths'], 
                    f'Trdmnt LIKE \'%____-__%\'', 'BETA_Mbeta', '1990-01-01', '2000-01-01')
data2 = csmar.query(['Stkcd', 'Trdmnt', 'IsNotBSE', 'Betaval', 'Betavals', 'TradingMonths'], 
                    f'Trdmnt LIKE \'%____-__%\'', 'BETA_Mbeta', '2000-01-01', '2010-01-01')
data3 = csmar.query(['Stkcd', 'Trdmnt', 'IsNotBSE', 'Betaval', 'Betavals', 'TradingMonths'], 
                    f'Trdmnt LIKE \'%____-__%\'', 'BETA_Mbeta', '2010-01-01', '2015-01-01')
data4 = csmar.query(['Stkcd', 'Trdmnt', 'IsNotBSE', 'Betaval', 'Betavals', 'TradingMonths'], 
                    f'Trdmnt LIKE \'%____-__%\'', 'BETA_Mbeta', '2015-01-01', '2020-01-01')
data5 = csmar.query(['Stkcd', 'Trdmnt', 'IsNotBSE', 'Betaval', 'Betavals', 'TradingMonths'], 
                    f'Trdmnt LIKE \'%____-__%\'', 'BETA_Mbeta', '2020-01-01', '2023-06-01')
df1 = pd.concat([pd.DataFrame(data1), pd.DataFrame(data2), pd.DataFrame(data3), pd.DataFrame(data4), pd.DataFrame(data5)], axis=0)
df1.rename({'Stkcd': '证券代码', 'Trdmnt': '月份', 'IsNotBSE': '是否剔除北交所股票', 'Betaval': '分市场月Beta值', 'Betavals': '综合市场月Beta值', 'TradingMonths': '交易月数'}, 
           axis='columns', inplace=True)
df1.drop_duplicates(subset=['证券代码', '月份', '是否剔除北交所股票'], inplace=True)
df1['证券代码'] = df1['证券代码'].astype('int')
df1 = df1.sort_values(by=['证券代码', '交易月份', '是否剔除北交所股票']).reset_index().drop(columns=['index'])
df2 = pd.merge(header, df1, on=['证券代码', '月份'], how='left')
df2['查询成功'] = 1
df2['查询成功'][df2['是否剔除北交所股票'].isna()] = 0
df3 = df2.drop(columns=['月份'])
df3.to_csv('../../data/csmar/月_月收益Beta表(48个月滚动).csv', index=False, encoding='utf-8-sig')
df3

           证券代码        交易月份  分市场月Beta值  综合市场月Beta值  是否剔除北交所股票  交易月数  查询成功
0             1  1990-01-31        NaN         NaN        NaN   NaN     0
1             1  1990-02-28        NaN         NaN        NaN   NaN     0
2             1  1990-03-31        NaN         NaN        NaN   NaN     0
3             1  1990-04-30        NaN         NaN        NaN   NaN     0
4             1  1990-05-31        NaN         NaN        NaN   NaN     0
...         ...         ...        ...         ...        ...   ...   ...
2197475  900957  2023-01-31        NaN         NaN        NaN   NaN     0
2197476  900957  2023-02-28        NaN         NaN        NaN   NaN     0
2197477  900957  2023-03-31        NaN         NaN        NaN   NaN     0
2197478  900957  2023-04-30        NaN         NaN        NaN   NaN     0
2197479  900957  2023-05-31        NaN         NaN        NaN   NaN     0

[2197480 rows x 7 columns]

In [41]:
# 个股交易数据 — 月个股回报率文件
# 本表数据总记录数：734624 条，数据频率：月度，数据开始时间： 1990-12，数据结束时间： 2023-05

data1 = csmar.query(['Stkcd', 'Trdmnt', 'Opndt', 'Mopnprc', 'Clsdt', 'Mclsprc', 'Mnshrtrd', 'Mnvaltrd', 'Msmvosd', 'Msmvttl', 'Ndaytrd', 'Mretwd', 'Mretnd', 'Markettype', 'Capchgdt', 'Ahshrtrd_M', 'Ahvaltrd_M'], 
                    f'Trdmnt LIKE \'%____-__%\'', 'TRD_Mnth', '1990-01-01', '1995-01-01')
data2 = csmar.query(['Stkcd', 'Trdmnt', 'Opndt', 'Mopnprc', 'Clsdt', 'Mclsprc', 'Mnshrtrd', 'Mnvaltrd', 'Msmvosd', 'Msmvttl', 'Ndaytrd', 'Mretwd', 'Mretnd', 'Markettype', 'Capchgdt', 'Ahshrtrd_M', 'Ahvaltrd_M'], 
                    f'Trdmnt LIKE \'%____-__%\'', 'TRD_Mnth', '1995-01-01', '2000-01-01')
data3 = csmar.query(['Stkcd', 'Trdmnt', 'Opndt', 'Mopnprc', 'Clsdt', 'Mclsprc', 'Mnshrtrd', 'Mnvaltrd', 'Msmvosd', 'Msmvttl', 'Ndaytrd', 'Mretwd', 'Mretnd', 'Markettype', 'Capchgdt', 'Ahshrtrd_M', 'Ahvaltrd_M'], 
                    f'Trdmnt LIKE \'%____-__%\'', 'TRD_Mnth', '2000-01-01', '2005-01-01')
data4 = csmar.query(['Stkcd', 'Trdmnt', 'Opndt', 'Mopnprc', 'Clsdt', 'Mclsprc', 'Mnshrtrd', 'Mnvaltrd', 'Msmvosd', 'Msmvttl', 'Ndaytrd', 'Mretwd', 'Mretnd', 'Markettype', 'Capchgdt', 'Ahshrtrd_M', 'Ahvaltrd_M'], 
                    f'Trdmnt LIKE \'%____-__%\'', 'TRD_Mnth', '2005-01-01', '2010-01-01')
data5 = csmar.query(['Stkcd', 'Trdmnt', 'Opndt', 'Mopnprc', 'Clsdt', 'Mclsprc', 'Mnshrtrd', 'Mnvaltrd', 'Msmvosd', 'Msmvttl', 'Ndaytrd', 'Mretwd', 'Mretnd', 'Markettype', 'Capchgdt', 'Ahshrtrd_M', 'Ahvaltrd_M'], 
                    f'Trdmnt LIKE \'%____-__%\'', 'TRD_Mnth', '2010-01-01', '2015-01-01')
data6 = csmar.query(['Stkcd', 'Trdmnt', 'Opndt', 'Mopnprc', 'Clsdt', 'Mclsprc', 'Mnshrtrd', 'Mnvaltrd', 'Msmvosd', 'Msmvttl', 'Ndaytrd', 'Mretwd', 'Mretnd', 'Markettype', 'Capchgdt', 'Ahshrtrd_M', 'Ahvaltrd_M'], 
                    f'Trdmnt LIKE \'%____-__%\'', 'TRD_Mnth', '2015-01-01', '2020-01-01')
data7 = csmar.query(['Stkcd', 'Trdmnt', 'Opndt', 'Mopnprc', 'Clsdt', 'Mclsprc', 'Mnshrtrd', 'Mnvaltrd', 'Msmvosd', 'Msmvttl', 'Ndaytrd', 'Mretwd', 'Mretnd', 'Markettype', 'Capchgdt', 'Ahshrtrd_M', 'Ahvaltrd_M'], 
                    f'Trdmnt LIKE \'%____-__%\'', 'TRD_Mnth', '2020-01-01', '2023-06-01')
df1 = pd.concat([pd.DataFrame(data1), pd.DataFrame(data2), pd.DataFrame(data3), pd.DataFrame(data4), pd.DataFrame(data5), pd.DataFrame(data6), pd.DataFrame(data7)], axis=0)
df1.rename({'Stkcd': '证券代码', 'Trdmnt': '月份', 'Opndt': '月开盘日期', 'Mopnprc': '月开盘价', 'Clsdt': '月收盘日期', 'Mclsprc': '月收盘价', 'Mnshrtrd': '月个股交易股数', 'Mnvaltrd': '月个股交易金额', 'Msmvosd': '月个股流通市值', 'Msmvttl': '月个股总市值', 'Ndaytrd': '月交易天数', 'Mretwd': '考虑现金红利再投资的月个股回报率', 'Mretnd': '不考虑现金红利再投资的月个股回报率', 'Markettype': '市场类型', 'Capchgdt': '最新股本变动日期', 'Ahshrtrd_M': '月盘后成交总量', 'Ahvaltrd_M': '月盘后成交总额'}, 
           axis='columns', inplace=True)
df1.drop_duplicates(subset=['证券代码', '月份'], inplace=True)
df1['证券代码'] = df1['证券代码'].astype('int')
df1 = df1.sort_values(by=['证券代码', '月份']).reset_index().drop(columns=['index'])
df2 = pd.merge(header, df1, on=['证券代码', '月份'], how='left')
df2['查询成功'] = 1
df2['查询成功'][df2['月开盘日期'].isna()] = 0
df3 = df2.drop(columns=['月份'])
df3.to_csv('../../data/csmar/月_月个股回报率文件.csv', index=False, encoding='utf-8-sig')
df3

,证券代码,交易月份,月开盘日期,月开盘价,月收盘日期,月收盘价,月个股交易股数,月个股交易金额,月个股流通市值,月个股总市值,月交易天数,考虑现金红利再投资的月个股回报率,不考虑现金红利再投资的月个股回报率,市场类型,最新股本变动日期,月盘后成交总量,月盘后成交总额,查询成功
0,1,1990-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,1990-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,1,1990-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,1,1990-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,1,1990-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2197475,900957,2023-01-31,03,0.568,31,0.585,3767181.0,2198566.0,107640.0,204165.0,16.0,0.037231,0.037234,2.0,2000-08-03,0,0.0,1
2197476,900957,2023-02-28,01,0.585,28,0.573,2730895.0,1583914.0,105432.0,199977.0,20.0,-0.020520,-0.020513,2.0,2000-08-03,0,0.0,1
2197477,900957,2023-03-31,01,0.573,31,0.527,3055292.0,1681507.0,96968.0,183923.0,23.0,-0.080282,-0.080279,2.0,2000-08-03,0,0.0,1
2197478,900957,2023-04-30,03,0.526,28,0.525,2270414.0,1179896.0,96600.0,183225.0,19.0,-0.003795,-0.003795,2.0,2000-08-03,0,0.0,1
2197479,900957,2023-05-31,04,0.520,31,0.509,2992963.0,1537800.0,93656.0,177641.0,20.0,-0.030478,-0.030476,2.0,2000-08-03,0,0.0,1

In [24]:
# 个股交易数据 — 周个股回报率文件
# 本表数据总记录数：3083428 条，数据频率：周度，数据开始时间： 1990-51，数据结束时间： 2023-22

df_list = []
start = '1990-01-01'
for y in range(1991, 2024):
    end = f'{y}-06-01'
    data = csmar.query(['Stkcd', 'Trdwnt', 'Opndt', 'Wopnprc', 'Clsdt', 'Wclsprc', 'Wnshrtrd', 'Wnvaltrd', 'Wsmvosd', 'Wsmvttl', 'Ndaytrd', 'Wretwd', 'Wretnd', 'Markettype', 'Capchgdt', 'Ahshrtrd_W', 'Ahvaltrd_W'], 
                       f'Trdwnt LIKE \'%____-__%\'', 'TRD_Week', start, end)
    df_list.append(pd.DataFrame(data))
    start = end

df1 = pd.concat(df_list, axis=0)
df1.rename({'Stkcd': '证券代码', 'Trdwnt': '交易周份', 'Opndt': '周开盘日期', 'Wopnprc': '周开盘价', 'Clsdt': '周收盘日期', 'Wclsprc': '周收盘价', 'Wnshrtrd': '周个股交易股数', 'Wnvaltrd': '周个股交易金额', 'Wsmvosd': '周个股流通市值', 'Wsmvttl': '周个股总市值', 'Ndaytrd': '周交易天数', 'Wretwd': '考虑现金红利再投资的周个股回报率', 'Wretnd': '不考虑现金红利再投资的周个股回报率', 'Markettype': '市场类型', 'Capchgdt': '最新股本变动日期', 'Ahshrtrd_W': '周盘后成交总量', 'Ahvaltrd_W': '周盘后成交总额'}, 
           axis='columns', inplace=True)
df1.drop_duplicates(subset=['证券代码', '交易周份'], inplace=True)
df1['证券代码'] = df1['证券代码'].astype('int')
df1 = df1.sort_values(by=['证券代码', '交易周份']).reset_index().drop(columns=['index'])
df1.to_csv('../../data/csmar/周_周个股回报率文件.csv', index=False, encoding='utf-8-sig')
df1

,证券代码,交易周份,周开盘日期,周开盘价,周收盘日期,周收盘价,周个股交易股数,周个股交易金额,周个股流通市值,周个股总市值,周交易天数,考虑现金红利再投资的周个股回报率,不考虑现金红利再投资的周个股回报率,市场类型,最新股本变动日期,周盘后成交总量,周盘后成交总额
0,1,1991-14,1991-04-03,49.000,1991-04-06,48.280,1300,64000.0,1279420.0,2341588.26,4,NaN,NaN,4,1991-04-03,NaN,NaN
1,1,1991-15,1991-04-08,48.040,1991-04-13,46.840,3400,161000.0,1241260.0,2271748.01,5,-0.029826,-0.029826,4,1991-04-03,NaN,NaN
2,1,1991-16,1991-04-16,46.380,1991-04-20,45.460,1400,64000.0,1204690.0,2204817.77,5,-0.029462,-0.029462,4,1991-04-03,NaN,NaN
3,1,1991-17,1991-04-23,45.000,1991-04-26,44.340,6700,300000.0,1175010.0,2150497.58,4,-0.024637,-0.024637,4,1991-04-03,NaN,NaN
4,1,1991-18,1991-04-29,43.900,1991-05-04,43.020,1300,57000.0,1140030.0,2086477.36,5,-0.029770,0.365088,4,1991-04-03,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992783,900957,2023-18,2023-05-04,0.520,2023-05-05,0.514,134200,69373.0,94576.0,179386.00,2,-0.020952,-0.020952,2,2000-08-03,0.0,0.0
992784,900957,2023-19,2023-05-08,0.508,2023-05-12,0.501,425000,216379.0,92184.0,174849.00,5,-0.025292,-0.025292,2,2000-08-03,0.0,0.0
992785,900957,2023-20,2023-05-15,0.501,2023-05-19,0.517,445163,228660.0,95128.0,180433.00,5,0.031937,0.031936,2,2000-08-03,0.0,0.0
992786,900957,2023-21,2023-05-22,0.515,2023-05-26,0.523,1418300,729919.0,96232.0,182527.00,5,0.011603,0.011605,2,2000-08-03,0.0,0.0
992787,900957,2023-22,2023-05-29,0.525,2023-06-02,0.505,903750,461017.0,92920.0,176245.00,5,-0.034417,-0.034417,2,2000-08-03,0.0,0.0