In [1]:
import numpy as np
import pandas as pd
from utils.diff import diff

In [2]:
# 33. herf
# 季度频率。行业内各公司的销售百分比的平方和。

df1 = pd.read_csv('../../data/csmar/季_利润表.csv', usecols=['证券代码', '会计期间', '营业总收入'])
df2 = pd.read_csv('../../data/csmar/公司文件.csv', usecols=['证券代码', '行业代码C'])
df3 = pd.merge(df1, df2, on=['证券代码'], how='left')
df3 = diff(df3, col=['营业总收入'])
df4 = df3[['行业代码C', '会计期间', '营业总收入']].groupby(['行业代码C', '会计期间']).sum()
df4.rename({'营业总收入':'行业营业总收入'}, axis='columns', inplace=True)
df5 = pd.merge(df3, df4, on=['行业代码C', '会计期间'], how='left')
df5['herf'] = (df5['营业总收入']/df5['行业营业总收入'].replace(0, np.nan))**2
df6 = df5[['证券代码', '会计期间', 'herf']]
df6.to_csv('../../output/csmar/季_33.csv', index=False, encoding='utf-8-sig')
df6

          证券代码        会计期间          herf
0            1  1990-03-31           NaN
1            1  1990-06-30           NaN
2            1  1990-09-30           NaN
3            1  1990-12-31           NaN
4            1  1991-03-31           NaN
...        ...         ...           ...
728835  900957  2022-03-31  7.850514e-09
728836  900957  2022-06-30  4.181544e-09
728837  900957  2022-09-30  3.954801e-09
728838  900957  2022-12-31  7.062829e-10
728839  900957  2023-03-31  7.358431e-09

[728840 rows x 3 columns]