In [1]:
import numpy as np
import pandas as pd

In [2]:
# 30. egr
# 季度频率。股本账面价值的季度变动百分比。

df1 = pd.read_csv('../../data/csmar/季_资产负债表.csv', usecols=['证券代码', '会计期间', '所有者权益合计'], low_memory=False)
df1['egr'] = (df1['所有者权益合计'] - df1.groupby('证券代码').shift(1)['所有者权益合计'])/df1.groupby('证券代码').shift(1)['所有者权益合计'].replace(0, np.nan)
df2 = df1[['证券代码', '会计期间', 'egr']]
df2.to_csv('../../output/csmar/季_30.csv', index=False, encoding='utf-8-sig')
df2

          证券代码        会计期间       egr
0            1  1990-03-31       NaN
1            1  1990-06-30       NaN
2            1  1990-09-30       NaN
3            1  1990-12-31       NaN
4            1  1991-03-31       NaN
...        ...         ...       ...
728835  900957  2022-03-31  0.014772
728836  900957  2022-06-30  0.026655
728837  900957  2022-09-30  0.015031
728838  900957  2022-12-31  0.018497
728839  900957  2023-03-31  0.015381

[728840 rows x 3 columns]