In [2]:
import numpy as np
import pandas as pd
from utils.diff import diff

In [3]:
# 09. cashdebt
# 季度频率。收益除以总负债，其定义类似于Ou和Penman(1989)[3]。
# 注：可定义为“息前税后利润”除以“负债总额”

df1 = pd.read_csv('../../data/csmar/季_现金流量表(直接法).csv', usecols=['证券代码', '会计期间', '经营活动产生的现金流量净额'], low_memory=False)
df2 = pd.read_csv('../../data/csmar/季_资产负债表.csv', usecols=['证券代码', '会计期间', '流动负债合计'], low_memory=False)
df3 = pd.merge(df1, df2, on=['证券代码', '会计期间'], how='left')
df3 = diff(df3, col=['经营活动产生的现金流量净额'])
df3['cashbebt'] = df3['经营活动产生的现金流量净额']/df3['流动负债合计'].replace(0, np.nan)
df4 = df3[['证券代码', '会计期间', 'cashbebt']]
df4.to_csv('../../output/csmar/季_9.csv', index=False, encoding='utf-8-sig')
df4

          证券代码        会计期间  cashbebt
0            1  1990-03-31       NaN
1            1  1990-06-30       NaN
2            1  1990-09-30       NaN
3            1  1990-12-31       NaN
4            1  1991-03-31       NaN
...        ...         ...       ...
728835  900957  2022-03-31 -0.018986
728836  900957  2022-06-30  0.064336
728837  900957  2022-09-30  0.106850
728838  900957  2022-12-31  0.520867
728839  900957  2023-03-31 -0.042398

[728840 rows x 3 columns]