In [1]:
import numpy as np
import pandas as pd
from utils.diff import diff

In [2]:
# 72. roic
# 季度频率。扣除利息和税项前的季度收益减去非营业收入，再除以非现金企业价值。

df1 = pd.read_csv('../../data/csmar/季_利润表.csv', usecols=['证券代码', '会计期间', '营业总收入', '其他业务收入', '查询成功'])
df1['其他业务收入'][df1['查询成功'].astype('bool')] = df1['其他业务收入'][df1['查询成功'].astype('bool')].fillna(0)
df1 = diff(df1, col=['营业总收入', '其他业务收入'])
df2 = pd.read_csv('../../data/csmar/季_资产负债表.csv', usecols=['证券代码', '会计期间', '存货净额', '固定资产净额', '无形资产净额'], low_memory=False)
df1['income'] = df1['营业总收入'] - df1['其他业务收入']
df2['noncash'] = df2['存货净额'] + df2['固定资产净额'] + df2['无形资产净额']
df3 = pd.merge(df1,df2,on=['证券代码', '会计期间'])
df3['roic'] = df3['income']/df3['noncash'].replace(0, np.nan)
df4 = df3[['证券代码', '会计期间', 'roic']]
df4.to_csv('../../output/csmar/季_72.csv', index=False, encoding='utf-8-sig')
df4

          证券代码        会计期间  roic
0            1  1990-03-31   NaN
1            1  1990-06-30   NaN
2            1  1990-09-30   NaN
3            1  1990-12-31   NaN
4            1  1991-03-31   NaN
...        ...         ...   ...
728835  900957  2022-03-31   NaN
728836  900957  2022-06-30   NaN
728837  900957  2022-09-30   NaN
728838  900957  2022-12-31   NaN
728839  900957  2023-03-31   NaN

[728840 rows x 3 columns]