In [1]:
import numpy as np
import pandas as pd
from utils.diff import diff

In [2]:
# 74.  salecash
# 季度频率。季度销售额除以现金和现金等价物。

df1 = pd.read_csv('../../data/csmar/季_资产负债表.csv', usecols=['证券代码', '会计期间', '货币资金'], low_memory=False)
df2 = pd.read_csv('../../data/csmar/季_利润表.csv', usecols=['证券代码', '会计期间', '营业收入'])
df3 = pd.merge(df1, df2, on=['证券代码', '会计期间'], how='left')
df3 = diff(df3, col=['营业收入'])
df3['salecash'] = df3['营业收入']/df3['货币资金'].replace(0, np.nan)
df4 = df3[['证券代码', '会计期间', 'salecash']]
df4.to_csv('../../output/csmar/季_74.csv', index=False, encoding='utf-8-sig')
df4

          证券代码        会计期间   salecash
0            1  1990-03-31        NaN
1            1  1990-06-30        NaN
2            1  1990-09-30        NaN
3            1  1990-12-31        NaN
4            1  1991-03-31        NaN
...        ...         ...        ...
728835  900957  2022-03-31  17.382531
728836  900957  2022-06-30  44.504232
728837  900957  2022-09-30  13.935888
728838  900957  2022-12-31   0.616411
728839  900957  2023-03-31   0.654342

[728840 rows x 3 columns]